// <auto-generated />
using System;
using GadgetHub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GadgetHub.Infrastructure.Migrations
{
    [DbContext(typeof(MyDBcontext))]
    [Migration("20251113102648_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GadgetHub.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-performance laptops for work and gaming",
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Latest smartphones with advanced features",
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Portable tablets for entertainment and work",
                            Name = "Tablets"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gadget accessories and peripherals",
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gaming consoles and accessories",
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Smart watches and fitness trackers",
                            Name = "Wearables"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Headphones, speakers, and audio equipment",
                            Name = "Audio"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Digital cameras and photography gear",
                            Name = "Cameras"
                        });
                });

            modelBuilder.Entity("GadgetHub.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Apple MacBook Pro with M3 Pro chip, 16GB RAM, 1TB SSD",
                            Name = "MacBook Pro 16\"",
                            Price = 2499.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dell XPS 13 with Intel i7, 16GB RAM, 512GB SSD",
                            Name = "Dell XPS 13",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "HP Spectre x360 2-in-1 laptop, 13.5\" OLED display",
                            Name = "HP Spectre x360",
                            Price = 1399.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Business laptop with Intel i5, 16GB RAM, 512GB SSD",
                            Name = "Lenovo ThinkPad X1",
                            Price = 1499.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Apple iPhone 15 Pro with A17 Pro chip, 256GB",
                            Name = "iPhone 15 Pro",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Samsung Galaxy S24 with Snapdragon 8 Gen 3, 256GB",
                            Name = "Samsung Galaxy S24",
                            Price = 899.99m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Google Pixel 8 Pro with Tensor G3, 256GB",
                            Name = "Google Pixel 8 Pro",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "OnePlus 12 with Snapdragon 8 Gen 3, 256GB",
                            Name = "OnePlus 12",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Apple iPad Air with M1 chip, 64GB, Wi-Fi",
                            Name = "iPad Air",
                            Price = 599.99m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Samsung Galaxy Tab S9, 256GB, 5G capable",
                            Name = "Samsung Galaxy Tab S9",
                            Price = 849.99m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Surface Pro 9 with Intel i5, 8GB RAM, 256GB SSD",
                            Name = "Microsoft Surface Pro 9",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Noise cancelling wireless earbuds with 30hr battery",
                            Name = "Wireless Earbuds",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "7-in-1 USB-C Hub with HDMI, USB, Ethernet ports",
                            Name = "USB-C Hub",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aluminum laptop stand adjustable for ergonomic use",
                            Name = "Laptop Stand",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Protective phone case with shock absorption",
                            Name = "Phone Case",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sony PlayStation 5 Console with DualSense controller",
                            Name = "PlayStation 5",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Microsoft Xbox Series X 1TB Console",
                            Name = "Xbox Series X",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nintendo Switch OLED Model with 7-inch screen",
                            Name = "Nintendo Switch OLED",
                            Price = 349.99m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wireless gaming headset with 7.1 surround sound",
                            Name = "Gaming Headset",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Apple Watch Series 9 GPS, 45mm, Aluminum",
                            Name = "Apple Watch Series 9",
                            Price = 399.99m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Samsung Galaxy Watch 6 Classic, 47mm",
                            Name = "Samsung Galaxy Watch 6",
                            Price = 369.99m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fitbit Charge 6 Fitness Tracker with GPS",
                            Name = "Fitbit Charge 6",
                            Price = 159.99m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 7,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
                            Name = "Sony WH-1000XM5",
                            Price = 399.99m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 7,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bose SoundLink Flex Bluetooth Speaker",
                            Name = "Bose SoundLink Flex",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Canon EOS R5 Mirrorless Camera, 45MP",
                            Name = "Canon EOS R5",
                            Price = 3899.99m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sony Alpha A7 IV Mirrorless Camera, 33MP",
                            Name = "Sony A7 IV",
                            Price = 2499.99m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 8,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "GoPro Hero 12 Action Camera with 5.3K video",
                            Name = "GoPro Hero 12",
                            Price = 399.99m
                        });
                });

            modelBuilder.Entity("GadgetHub.Domain.Entities.Product", b =>
                {
                    b.HasOne("GadgetHub.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GadgetHub.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
